version: '3.8'
services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:15.0.2
    command: -b 0.0.0.0
    ports:
      - "8088:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
